spring.application.name=lojaVirtual

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.datasource.url=jdbc:mysql://localhost:3306/lojaVirtual?useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:caroline}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
